FROM balenalib/raspberrypi3

WORKDIR /usr/src
COPY . .
COPY 3rdparty/piboto/Piboto-Regular.ttf /usr/share/fonts/truetype/piboto/Piboto-Regular.ttf

RUN install_packages \
  cmake \
  g++ \
  libavutil-dev \
  libavcodec-dev \
  libavformat-dev \
  libsdl2-dev \
  libsdl2-ttf-2.0-0 \
  libsdl2-ttf-dev \
  make \
  xorg

RUN mkdir -p /usr/src/build
RUN cd /usr/src/build && (cmake /usr/src || true) && make

CMD ["startx", "/usr/src/build/ThermalCamera"]